language: ruby
rvm:
  - 2.0.0
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
bundler_args: --without doc guard --jobs 7
before_install:
  - sudo apt-get install -qq libgecode-dev
script: 'bundle exec thor spec:ci'
