language: ruby

rvm:
  - 2.0.0
  - 2.1

notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true

bundler_args: --without doc guard --jobs 7

script: bundle exec rake
